package flagset

import (
	"encoding"
	"net"
	"time"

	"github.com/spf13/pflag"
)

type Interface interface {
	AddFlagSet(newSet *pflag.FlagSet)
	BoolSliceVar(p *[]bool, name string, value []bool, usage string)
	BoolSliceVarP(p *[]bool, name, shorthand string, value []bool, usage string)
	BoolVar(p *bool, name string, value bool, usage string)
	BoolVarP(p *bool, name, shorthand string, value bool, usage string)
	BytesBase64Var(p *[]byte, name string, value []byte, usage string)
	BytesBase64VarP(p *[]byte, name, shorthand string, value []byte, usage string)
	BytesHexVar(p *[]byte, name string, value []byte, usage string)
	BytesHexVarP(p *[]byte, name, shorthand string, value []byte, usage string)
	CountVar(p *int, name string, usage string)
	CountVarP(p *int, name, shorthand string, usage string)
	DurationSliceVar(p *[]time.Duration, name string, value []time.Duration, usage string)
	DurationSliceVarP(p *[]time.Duration, name, shorthand string, value []time.Duration, usage string)
	DurationVar(p *time.Duration, name string, value time.Duration, usage string)
	DurationVarP(p *time.Duration, name, shorthand string, value time.Duration, usage string)
	Float32SliceVar(p *[]float32, name string, value []float32, usage string)
	Float32SliceVarP(p *[]float32, name, shorthand string, value []float32, usage string)
	Float32Var(p *float32, name string, value float32, usage string)
	Float32VarP(p *float32, name, shorthand string, value float32, usage string)
	Float64SliceVar(p *[]float64, name string, value []float64, usage string)
	Float64SliceVarP(p *[]float64, name, shorthand string, value []float64, usage string)
	Float64Var(p *float64, name string, value float64, usage string)
	Float64VarP(p *float64, name, shorthand string, value float64, usage string)
	Int16Var(p *int16, name string, value int16, usage string)
	Int16VarP(p *int16, name, shorthand string, value int16, usage string)
	Int32SliceVar(p *[]int32, name string, value []int32, usage string)
	Int32SliceVarP(p *[]int32, name, shorthand string, value []int32, usage string)
	Int32Var(p *int32, name string, value int32, usage string)
	Int32VarP(p *int32, name, shorthand string, value int32, usage string)
	Int64SliceVar(p *[]int64, name string, value []int64, usage string)
	Int64SliceVarP(p *[]int64, name, shorthand string, value []int64, usage string)
	Int64Var(p *int64, name string, value int64, usage string)
	Int64VarP(p *int64, name, shorthand string, value int64, usage string)
	Int8Var(p *int8, name string, value int8, usage string)
	Int8VarP(p *int8, name, shorthand string, value int8, usage string)
	IntSliceVar(p *[]int, name string, value []int, usage string)
	IntSliceVarP(p *[]int, name, shorthand string, value []int, usage string)
	IntVar(p *int, name string, value int, usage string)
	IntVarP(p *int, name, shorthand string, value int, usage string)
	IPMaskVar(p *net.IPMask, name string, value net.IPMask, usage string)
	IPMaskVarP(p *net.IPMask, name, shorthand string, value net.IPMask, usage string)
	IPNetSliceVar(p *[]net.IPNet, name string, value []net.IPNet, usage string)
	IPNetSliceVarP(p *[]net.IPNet, name, shorthand string, value []net.IPNet, usage string)
	IPNetVar(p *net.IPNet, name string, value net.IPNet, usage string)
	IPNetVarP(p *net.IPNet, name, shorthand string, value net.IPNet, usage string)
	IPSliceVar(p *[]net.IP, name string, value []net.IP, usage string)
	IPSliceVarP(p *[]net.IP, name, shorthand string, value []net.IP, usage string)
	IPVar(p *net.IP, name string, value net.IP, usage string)
	IPVarP(p *net.IP, name, shorthand string, value net.IP, usage string)
	StringArrayVar(p *[]string, name string, value []string, usage string)
	StringArrayVarP(p *[]string, name, shorthand string, value []string, usage string)
	StringSliceVar(p *[]string, name string, value []string, usage string)
	StringSliceVarP(p *[]string, name, shorthand string, value []string, usage string)
	StringToInt64Var(p *map[string]int64, name string, value map[string]int64, usage string)
	StringToInt64VarP(p *map[string]int64, name, shorthand string, value map[string]int64, usage string)
	StringToIntVar(p *map[string]int, name string, value map[string]int, usage string)
	StringToIntVarP(p *map[string]int, name, shorthand string, value map[string]int, usage string)
	StringToStringVar(p *map[string]string, name string, value map[string]string, usage string)
	StringToStringVarP(p *map[string]string, name, shorthand string, value map[string]string, usage string)
	StringVar(p *string, name string, value string, usage string)
	StringVarP(p *string, name, shorthand string, value string, usage string)
	TextVar(p encoding.TextUnmarshaler, name string, value encoding.TextMarshaler, usage string)
	TextVarP(p encoding.TextUnmarshaler, name, shorthand string, value encoding.TextMarshaler, usage string)
	TimeVar(p *time.Time, name string, value time.Time, formats []string, usage string)
	TimeVarP(p *time.Time, name, shorthand string, value time.Time, formats []string, usage string)
	Uint16Var(p *uint16, name string, value uint16, usage string)
	Uint16VarP(p *uint16, name, shorthand string, value uint16, usage string)
	Uint32Var(p *uint32, name string, value uint32, usage string)
	Uint32VarP(p *uint32, name, shorthand string, value uint32, usage string)
	Uint64Var(p *uint64, name string, value uint64, usage string)
	Uint64VarP(p *uint64, name, shorthand string, value uint64, usage string)
	Uint8Var(p *uint8, name string, value uint8, usage string)
	Uint8VarP(p *uint8, name, shorthand string, value uint8, usage string)
	UintSliceVar(p *[]uint, name string, value []uint, usage string)
	UintSliceVarP(p *[]uint, name, shorthand string, value []uint, usage string)
	UintVar(p *uint, name string, value uint, usage string)
	UintVarP(p *uint, name, shorthand string, value uint, usage string)
	Var(value pflag.Value, name string, usage string)
	VarP(value pflag.Value, name, shorthand string, usage string)
}

var _ Interface = (*pflag.FlagSet)(nil)
