# This file was generated by GoReleaser. DO NOT EDIT.
cask "rageta" do
  name "rageta"
  desc "Cloud native pipelines"
  homepage "https://github.com/raffis/rageta"
  version "0.0.46"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rageta"

  on_macos do
    on_intel do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_darwin_amd64.tar.gz"
      sha256 "2598ed1d93cb63be70294d12472743b6563ccdad770403c07df212f7fba9e15c"
    end
    on_arm do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_darwin_arm64.tar.gz"
      sha256 "c35456f5b8f8c0e7c83e865f514f432439e627cd229eeebc6d4f2dcb1e7c6696"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_linux_amd64.tar.gz"
      sha256 "d5c8435e44d8188c1c9b6d83eb3ef64def753452aa9ed8a1af5536b9da29ed10"
    end
    on_arm do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_linux_arm64.tar.gz"
      sha256 "fe7c399d6d349d6f514d04353e85b203ced50995b5d850155f160e5c56612917"
    end
  end

  # No zap stanza required
end
