# This file was generated by GoReleaser. DO NOT EDIT.
cask "rageta" do
  name "rageta"
  desc "Cloud native pipelines"
  homepage "https://github.com/raffis/rageta"
  version "0.0.44"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rageta"

  on_macos do
    on_intel do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_darwin_amd64.tar.gz"
      sha256 "4e6074f8d7615240f7664e11c28ceda74e57676748c6636bcef81052e2c1a9b4"
    end
    on_arm do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_darwin_arm64.tar.gz"
      sha256 "6887c2bf665a1f76e89801b3332f18a5493e4830eb95b39171de24a0d2c77196"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_linux_amd64.tar.gz"
      sha256 "48f3bf2c587f6fbcb0848c62584d8e117e8004f0d7c138750e400086544e7c25"
    end
    on_arm do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_linux_arm64.tar.gz"
      sha256 "8e2387e25bb5582583a3bf5f531fbb0ed71eadfa59b233ac736bb8e01191590b"
    end
  end

  # No zap stanza required
end
