# This file was generated by GoReleaser. DO NOT EDIT.
cask "rageta" do
  name "rageta"
  desc "Cloud native pipelines"
  homepage "https://github.com/raffis/rageta"
  version "0.0.47"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rageta"

  on_macos do
    on_intel do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_darwin_amd64.tar.gz"
      sha256 "0a96c5081678f32fa21198b5895eabc6727de3ef9c3a7627e80b5cb69c5e2d02"
    end
    on_arm do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_darwin_arm64.tar.gz"
      sha256 "294756bef566a633398684c16280fc58d5d01f24c4d40daba191d7e6b76fbad0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_linux_amd64.tar.gz"
      sha256 "f58cd6fd50e7562f32663a5fc4da01a9701163f839ef407cfd2e8782b0f3f727"
    end
    on_arm do
      url "https://github.com/raffis/rageta/releases/download/v#{version}/rageta_#{version}_linux_arm64.tar.gz"
      sha256 "19dccb95e90f9e4de441e8a70c8332306f0f8e35fa858da4b8f9a745b34e0d9f"
    end
  end

  # No zap stanza required
end
