// Package lint validates pipeline manifests against the generated
// core.rageta.io Pipeline CRD schema.
//
// It deliberately avoids k8s.io/apiextensions-apiserver: that module's
// validation helpers pull in k8s.io/apiserver (CEL, feature gates, admission,
// etc.) and noticeably inflate binary size. A CRD's openAPIV3Schema is,
// however, already shaped like a plain JSON Schema (properties/required/
// items/enum/...), so it can be unmarshaled directly into
// k8s.io/kube-openapi's spec.Schema - a dependency already pulled in
// transitively by k8s.io/apimachinery - and validated with kube-openapi's
// validator. No extra module is required.
package lint

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/raffis/rageta/crds"
	"k8s.io/kube-openapi/pkg/validation/spec"
	"k8s.io/kube-openapi/pkg/validation/strfmt"
	"k8s.io/kube-openapi/pkg/validation/validate"
	"sigs.k8s.io/yaml"
)

const pipelineCRDFile = "core.rageta.io_pipelines.yaml"

type crdVersion struct {
	Name   string `json:"name"`
	Schema struct {
		OpenAPIV3Schema *spec.Schema `json:"openAPIV3Schema"`
	} `json:"schema"`
}

type crdDocument struct {
	Spec struct {
		Group    string `json:"group"`
		Names    struct {
			Kind string `json:"kind"`
		} `json:"names"`
		Versions []crdVersion `json:"versions"`
	} `json:"spec"`
}

var (
	loadOnce     sync.Once
	loadErr      error
	crdGroup     string
	crdKind      string
	schemasByVer map[string]*spec.Schema
)

func load() {
	raw, err := crds.FS.ReadFile(pipelineCRDFile)
	if err != nil {
		loadErr = fmt.Errorf("failed to read embedded pipeline CRD: %w", err)
		return
	}

	jsonBytes, err := yaml.YAMLToJSON(raw)
	if err != nil {
		loadErr = fmt.Errorf("failed to parse embedded pipeline CRD: %w", err)
		return
	}

	var crd crdDocument
	if err := json.Unmarshal(jsonBytes, &crd); err != nil {
		loadErr = fmt.Errorf("failed to parse embedded pipeline CRD: %w", err)
		return
	}

	crdGroup = crd.Spec.Group
	crdKind = crd.Spec.Names.Kind
	schemasByVer = make(map[string]*spec.Schema, len(crd.Spec.Versions))

	for _, version := range crd.Spec.Versions {
		if version.Schema.OpenAPIV3Schema == nil {
			continue
		}
		closeUnknownFields(version.Schema.OpenAPIV3Schema)
		schemasByVer[version.Name] = version.Schema.OpenAPIV3Schema
	}
}

// closeUnknownFields recursively marks every fixed-shape object schema
// (one with declared properties) as closed to unknown fields, unless it is
// explicitly opted out via x-kubernetes-preserve-unknown-fields. The CRD as
// generated by controller-gen leaves additionalProperties unset, relying on
// the real Kubernetes API server's structural-schema field pruning to drop
// unrecognized fields - a mechanism we don't have here since we avoid
// k8s.io/apiextensions-apiserver. Setting additionalProperties: false
// ourselves makes the plain JSON-schema validator reject typos and unknown
// fields instead of silently ignoring them.
func closeUnknownFields(s *spec.Schema) {
	if s == nil {
		return
	}

	if preserveUnknownFields(s) {
		return
	}

	if len(s.Properties) > 0 && s.AdditionalProperties == nil {
		s.AdditionalProperties = &spec.SchemaOrBool{Allows: false}
	}

	for name, prop := range s.Properties {
		closeUnknownFields(&prop)
		s.Properties[name] = prop
	}

	if s.AdditionalProperties != nil {
		closeUnknownFields(s.AdditionalProperties.Schema)
	}

	if s.Items != nil {
		closeUnknownFields(s.Items.Schema)
		for i := range s.Items.Schemas {
			closeUnknownFields(&s.Items.Schemas[i])
		}
	}

	for i := range s.AllOf {
		closeUnknownFields(&s.AllOf[i])
	}
	for i := range s.OneOf {
		closeUnknownFields(&s.OneOf[i])
	}
	for i := range s.AnyOf {
		closeUnknownFields(&s.AnyOf[i])
	}
	closeUnknownFields(s.Not)
}

func preserveUnknownFields(s *spec.Schema) bool {
	v, ok := s.Extensions["x-kubernetes-preserve-unknown-fields"]
	if !ok {
		return false
	}
	b, ok := v.(bool)
	return ok && b
}

// Validate checks a pipeline manifest (YAML or JSON) against the embedded
// core.rageta.io Pipeline CRD schema.
func Validate(manifest []byte) error {
	loadOnce.Do(load)
	if loadErr != nil {
		return loadErr
	}

	jsonBytes, err := yaml.YAMLToJSON(manifest)
	if err != nil {
		return fmt.Errorf("failed to parse manifest: %w", err)
	}

	var obj map[string]interface{}
	if err := json.Unmarshal(jsonBytes, &obj); err != nil {
		return fmt.Errorf("failed to parse manifest: %w", err)
	}

	apiVersion, _ := obj["apiVersion"].(string)
	kind, _ := obj["kind"].(string)

	group, version, _ := strings.Cut(apiVersion, "/")
	if group != crdGroup || kind != crdKind {
		return fmt.Errorf("manifest is not a %s/<version> %s (found apiVersion %q, kind %q)", crdGroup, crdKind, apiVersion, kind)
	}

	schema, ok := schemasByVer[version]
	if !ok {
		return fmt.Errorf("unsupported apiVersion %q for kind %q", apiVersion, kind)
	}

	result := validate.NewSchemaValidator(schema, nil, "", strfmt.Default).Validate(obj)
	if len(result.Errors) > 0 {
		return errors.Join(result.Errors...)
	}

	return nil
}
