# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rageta < Formula
  desc "Cloud native pipelines"
  homepage "https://github.com/raffis/rageta"
  version "0.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raffis/rageta/releases/download/v0.0.23/rageta_0.0.23_darwin_amd64.tar.gz"
      sha256 "580f7ee5d7910a1ba8f97c1769cb0b63281d450b73fcfb00b0e709fa671ac924"

      def install
        bin.install "rageta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raffis/rageta/releases/download/v0.0.23/rageta_0.0.23_darwin_arm64.tar.gz"
      sha256 "33ed7f94406f68fdcbaeb9d960b86dd0f06b0d6e99735b4288a526120a2f84d0"

      def install
        bin.install "rageta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/rageta/releases/download/v0.0.23/rageta_0.0.23_linux_amd64.tar.gz"
      sha256 "800b899f0afd0488dc86751ac0741196b9aabfebcf46ace140cadc69dd7c21ba"
      def install
        bin.install "rageta"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/rageta/releases/download/v0.0.23/rageta_0.0.23_linux_arm64.tar.gz"
      sha256 "252f821c274d24c703b2afb08f9128c7f3abd7017968044de4804929c749f82c"
      def install
        bin.install "rageta"
      end
    end
  end

  test do
    system "#{bin}/rageta -h"
  end
end
