apiVersion: core.rageta.io/v1beta1
kind: Pipeline

metadata:
  name: kubebuilder

templates:
- name: golang
  volumeMounts:
  - mountPath: /go/pkg/mod
    cache:
      name: go-mod
  - mountPath: /root/.cache/go-build
    cache:
      name: go-build
  sources:
  - local:
      path: .
      to: .
  image: golang:1.25-alpine
  workingDir: /workspace

tasks:
- name: go
  inherit:
    pipeline: ./examples/golang.yaml
- name: generate
  templates:
  - name: golang
  artifacts:
  - local:
      path: ./crds/*
      to: crds
  steps:
  - script: go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.20.0
  - script: controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=crds
  - script: controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./pkg/apis/core/...; ./pkg/apis/package/...; ./internal/processor/..."
- name: code-gen
  artifacts:
  - local:
      path: ./*
      to: .
  steps:
  - script: ./hack/code-gen.sh