name: pr-build
on:
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            sleep 1
            echo "Inside group"
            sleep 1
            echo "::group::My title 2"
            echo "Inside group"
            sleep 1
            echo "Inside group"
            sleep 1
            echo "Inside group"
            sleep 1
            echo "Inside group"
            sleep 1
            echo "Inside group"
            sleep 1
            echo "Inside group"
            echo "Inside group"
            echo "Inside group"
            echo "Inside group"
            echo "::endgroup::"    
            echo "Inside group 2"
            sleep 1
            echo "Inside group 2"
            sleep 1
            echo "::endgroup::"    
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1      
      - run: |
          curl -L -v https://github.com/raffis/rageta/releases/download/v0.0.1-alpha/rageta-osx -o rageta-osx; chmod +x rageta-osx; ./rageta-osx version 
          brew install docker
          #colima delete --force
          colima start
          #ls -hals /Users/runner/.colima
          export DOCKER_HOST="unix:///Users/runner/.colima/docker.sock"
          #export
          #sleep 1
          #colima version
          #docker info

          
          docker run --workdir "/__rootfs/$HOME" --user=$UID -v $HOME:/__rootfs/$HOME bash -c "ls -hals /__rootfs/$HOME"

          export TMPDIR=/tmp/colima
          ./rageta-osx run --log-level=debug --no-gc --tee  test10 -o prompt -- _x/ || true
          echo "-------"
          docker ps
          
          docker ps -q | xargs -L 1 docker logs          

    timeout-minutes: 45
